language: python
os: linux
python:
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coveralls

before_script:
  - python manage.py migrate
# after script

script:
  - black . --check
  - flake8 --max-line-length=88

deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_ACCESS_SECRET
    region: $AWS_DEPLOY_REGION
    app: $AWS_APP_NAME
    env: $AWS_APP_ENV
    bucket_name: $AWS_BUCKET_NAME
    on:
      branch: main